export const dom = {
  errorBanner: document.getElementById("errorBanner"),
  chatContainer: document.getElementById("chatContainer"),
  centerArea: document.getElementById("centerArea"),
  micBigBtn: document.getElementById("micBigBtn"),
  micLabel: document.getElementById("micLabel"),
  inputArea: document.getElementById("inputArea"),
  userInput: document.getElementById("userInput"),
  sendBtn: document.getElementById("sendBtn"),
  welcomeMsg: document.getElementById("welcomeMsg"),
  chipsBar: document.getElementById("chipsBar"),
  featureCards: document.getElementById("featureCards"),
  commandPalette: document.getElementById("commandPalette"),
  commandInput: document.getElementById("commandInput"),
  commandResults: document.getElementById("commandResults"),
  nucleusCanvas: document.getElementById("nucleusCanvas"),
  // Service status elements
  statusDotGemini: document.getElementById("statusDotGemini"),
  statusTextGemini: document.getElementById("statusTextGemini"),
  statusDotTelegram: document.getElementById("statusDotTelegram"),
  statusTextTelegram: document.getElementById("statusTextTelegram"),
  statusDotBrowser: document.getElementById("statusDotBrowser"),
  statusTextBrowser: document.getElementById("statusTextBrowser"),
  statusDotMastra: document.getElementById("statusDotMastra"),
  statusTextMastra: document.getElementById("statusTextMastra"),
};
