export const state = {
  ws: null,
  isConnected: false,
  isListening: false,
  audioContext: null,
  micStream: null,
  micWorkletNode: null,
  micSource: null,
  isSessionActive: false,
  accumulatedAssistantText: "",
  currentAssistantMsg: null,
  outputAudioContext: null,
  audioQueue: [],
  isPlaying: false,
  currentSource: null,
  isScreenSharing: false,
  coreSpeed: 1.0,
  coreSensitivity: 1.0,
  coreHue: 0,
  coreTheme: 'nebula',
  sidebarCollapsed: false,
  serviceStatus: {
    gemini: 'disconnected',
    telegram: 'disconnected',
    browser: 'disconnected',
    mastra: 'disconnected',
  },
  commands: [
    { id: 'weather', name: 'Check Weather' },
    { id: 'search', name: 'Web Search' },
    { id: 'tg-send', name: 'Send Telegram Message' },
    { id: 'tg-read', name: 'Read Telegram Messages' },
    { id: 'youtube', name: 'YouTube Search' },
    { id: 'browse', name: 'Browse Website' },
    { id: 'settings', name: 'Open Settings' },
    { id: 'toggle-sidebar', name: 'Toggle Sidebar' },
    { id: 'clear-chat', name: 'Clear Chat' },
  ],
};
