export const state = {
  ws: null,
  isConnected: false,
  isListening: false,
  audioContext: null,
  micStream: null,
  micWorkletNode: null,
  micSource: null,
  isSessionActive: false,
  accumulatedAssistantText: "",
  currentAssistantMsg: null,
  outputAudioContext: null,
  audioQueue: [],
  isPlaying: false,
  currentSource: null,
  isScreenSharing: false,
  coreSpeed: 1.0,
  coreSensitivity: 1.0,
  coreHue: 0,
  coreTheme: 'nebula',
};
